### ISSUE TITLE
使用 CNAME 方式代理 pximg 失效，返回 421 Misdirected Request

### ISSUE THREAD

**Issue by asadahimeka** [lrhtony/pixiv#11]
如题，不知道这种代理方式还行不行得通

![image](https://github.com/user-attachments/assets/fe39feb2-40e5-4008-9822-c927ce7a79a7)

**Comment by lrhtony** [comment]
Pixiv那边增加了对Header Host的检测
Cloudflare那边利用页面规则修改Host要加钱
只能用worker反代或者找免费修改Host的cdn (gcore)
但都有每月使用量的限制

**Comment by asadahimeka** [comment]
确实没啥好办法了[允悲]
